FORMAT: 1A
HOST: http://saltoverflow.apiblueprint.org/

# SaltOverflow

SaltOverflow backend API.

## Players Collection [/players]

### List All Players [GET]

+ Response 200 (application/json)

        [
            {
                "name": "RY",
                "played_characters": [54, 19, 31],
                "salt": 76,
                "win_percent": 47,
                "games_played": 21,
                "sessions_played": 5,
            }
        ]
            
## Games Collection [/games]

### List All Games [GET]

+ Response 200 (application/json)

        [
            {
                "players": [
                    {
                        "name": "RY",
                    },
                    {
                        "name": "Petate",
                    },
                ],
                "characters": [19, 31],
                "score": [1, 2],
                "session": 3,
            }
        ]